<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductApp.DataAccess\ProductApp.DataAccess.csproj" />
    <ProjectReference Include="..\ProductApp.Entities\ProductApp.Entities.csproj" />
  </ItemGroup>

</Project>
